# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_DiagnosisWindow(object):
    def setupUi(self, DiagnosisWindow):
        DiagnosisWindow.setObjectName("DiagnosisWindow")
        DiagnosisWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(DiagnosisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 120, 161, 46))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.batuk3minggu = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.batuk3minggu.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu.setObjectName("batuk3minggu")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.batuk3minggu.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.batuk3minggu.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(90, 170, 161, 46))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.batuk3minggu_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.batuk3minggu_2.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_2.setObjectName("batuk3minggu_2")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.batuk3minggu_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_23 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_23.setObjectName("radioButton_23")
        self.horizontalLayout_12.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_24.setObjectName("radioButton_24")
        self.horizontalLayout_12.addWidget(self.radioButton_24)
        self.batuk3minggu_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(90, 220, 161, 46))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.batuk3minggu_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.batuk3minggu_3.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_3.setObjectName("batuk3minggu_3")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.batuk3minggu_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_25 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_25.setObjectName("radioButton_25")
        self.horizontalLayout_13.addWidget(self.radioButton_25)
        self.radioButton_26 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_26.setObjectName("radioButton_26")
        self.horizontalLayout_13.addWidget(self.radioButton_26)
        self.batuk3minggu_3.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(90, 320, 161, 46))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.batuk3minggu_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.batuk3minggu_4.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_4.setObjectName("batuk3minggu_4")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.batuk3minggu_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radioButton_27 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_27.setObjectName("radioButton_27")
        self.horizontalLayout_14.addWidget(self.radioButton_27)
        self.radioButton_28 = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioButton_28.setObjectName("radioButton_28")
        self.horizontalLayout_14.addWidget(self.radioButton_28)
        self.batuk3minggu_4.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(90, 270, 161, 46))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.batuk3minggu_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.batuk3minggu_6.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_6.setObjectName("batuk3minggu_6")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.batuk3minggu_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.gridLayoutWidget_6)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.gridLayoutWidget_6)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_4.addWidget(self.radioButton_8)
        self.batuk3minggu_6.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(370, 120, 161, 46))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.batuk3minggu_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.batuk3minggu_7.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_7.setObjectName("batuk3minggu_7")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.batuk3minggu_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_9 = QtWidgets.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_5.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_5.addWidget(self.radioButton_10)
        self.batuk3minggu_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(370, 170, 161, 46))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.batuk3minggu_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.batuk3minggu_8.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_8.setObjectName("batuk3minggu_8")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.batuk3minggu_8.addWidget(self.label_15, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radioButton_31 = QtWidgets.QRadioButton(self.gridLayoutWidget_8)
        self.radioButton_31.setObjectName("radioButton_31")
        self.horizontalLayout_16.addWidget(self.radioButton_31)
        self.radioButton_32 = QtWidgets.QRadioButton(self.gridLayoutWidget_8)
        self.radioButton_32.setObjectName("radioButton_32")
        self.horizontalLayout_16.addWidget(self.radioButton_32)
        self.batuk3minggu_8.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(370, 220, 161, 46))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.batuk3minggu_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.batuk3minggu_9.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_9.setObjectName("batuk3minggu_9")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.batuk3minggu_9.addWidget(self.label_16, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.radioButton_33 = QtWidgets.QRadioButton(self.gridLayoutWidget_9)
        self.radioButton_33.setObjectName("radioButton_33")
        self.horizontalLayout_17.addWidget(self.radioButton_33)
        self.radioButton_34 = QtWidgets.QRadioButton(self.gridLayoutWidget_9)
        self.radioButton_34.setObjectName("radioButton_34")
        self.horizontalLayout_17.addWidget(self.radioButton_34)
        self.batuk3minggu_9.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(370, 270, 161, 46))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.batuk3minggu_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.batuk3minggu_10.setContentsMargins(0, 0, 0, 0)
        self.batuk3minggu_10.setObjectName("batuk3minggu_10")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.batuk3minggu_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_11 = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_6.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_6.addWidget(self.radioButton_12)
        self.batuk3minggu_10.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.btnDiagnosis = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiagnosis.setGeometry(QtCore.QRect(370, 330, 75, 23))
        self.btnDiagnosis.setObjectName("btnDiagnosis")

        #btn keluar edit
        self.btnKeluar = QtWidgets.QPushButton(self.centralwidget)
        self.btnKeluar.setGeometry(QtCore.QRect(450, 330, 75, 23))
        self.btnKeluar.setObjectName("btnKeluar")
        self.btnKeluar.clicked.connect(self.show_popup)
        self.btnKeluar.clicked.connect(DiagnosisWindow.close)

        DiagnosisWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DiagnosisWindow)
        self.statusbar.setObjectName("statusbar")
        DiagnosisWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DiagnosisWindow)
        QtCore.QMetaObject.connectSlotsByName(DiagnosisWindow)

    def retranslateUi(self, DiagnosisWindow):
        _translate = QtCore.QCoreApplication.translate
        DiagnosisWindow.setWindowTitle(_translate("DiagnosisWindow", "MainWindow"))
        self.label.setText(_translate("DiagnosisWindow", "Keluhan pasien :"))
        self.radioButton_2.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_2.setText(_translate("DiagnosisWindow", "Batuk >3 minggu"))
        self.label_11.setText(_translate("DiagnosisWindow", "Demam meriang"))
        self.radioButton_23.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_24.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_12.setText(_translate("DiagnosisWindow", "Batuk berdarah"))
        self.radioButton_25.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_26.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_13.setText(_translate("DiagnosisWindow", "Sesak nafas"))
        self.radioButton_27.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_28.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_3.setText(_translate("DiagnosisWindow", "Nyeri dada"))
        self.radioButton_7.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_8.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_4.setText(_translate("DiagnosisWindow", "Badan lemas"))
        self.radioButton_9.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_10.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_15.setText(_translate("DiagnosisWindow", "Nafsu makan menurun"))
        self.radioButton_31.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_32.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_16.setText(_translate("DiagnosisWindow", "Berat badan menurun"))
        self.radioButton_33.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_34.setText(_translate("DiagnosisWindow", "Tidak"))
        self.label_5.setText(_translate("DiagnosisWindow", "Berkeringat dimalam hari"))
        self.radioButton_11.setText(_translate("DiagnosisWindow", "Ya"))
        self.radioButton_12.setText(_translate("DiagnosisWindow", "Tidak"))
        self.btnDiagnosis.setText(_translate("DiagnosisWindow", "Diagnosis"))
        self.btnKeluar.setText(_translate("DiagnosisWindow", "Keluar"))

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("Apakah anda yakin akan keluar?")
        msg.setIcon(QMessageBox.Warning)
        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiagnosisWindow = QtWidgets.QMainWindow()
    ui = Ui_DiagnosisWindow()
    ui.setupUi(DiagnosisWindow)
    DiagnosisWindow.show()
    sys.exit(app.exec_())

